version: '3.8'
services:
  media-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./media:/usr/src/app/media
      - ./website:/usr/src/app/website
